version: '3.8'
services:
  app:
    image: aoirint/lastfm_api_middleware
    build: .
    restart: always
    environment:
      LASTFM_USER: ${LASTFM_USER}
      LASTFM_API_KEY: ${LASTFM_API_KEY}
      DUMP_PATH: ${DUMP_PATH}
      CORS_ALLOW_ORIGINS: ${CORS_ALLOW_ORIGINS}
    volumes:
      - "${HOST_DATA_DIR}:/data"
    ports:
      - "${HOST_PORT}:8000"
